module.exports = class Data1666199791692 {
  name = 'Data1666199791692'

  async up(db) {
    await db.query(`CREATE TABLE "factory" ("id" character varying NOT NULL, "pool_count" integer NOT NULL, "tx_count" integer NOT NULL, "total_volume_usd" numeric NOT NULL, "total_volume_eth" numeric NOT NULL, "total_fees_usd" numeric NOT NULL, "total_fees_eth" numeric NOT NULL, "untracked_volume_usd" numeric NOT NULL, "total_value_locked_usd" numeric NOT NULL, "total_value_locked_eth" numeric NOT NULL, "total_value_locked_usd_untracked" numeric NOT NULL, "total_value_locked_eth_untracked" numeric NOT NULL, "owner" text NOT NULL, CONSTRAINT "PK_1372e5a7d114a3fa80736ba66bb" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "bundle" ("id" character varying NOT NULL, "eth_price_usd" numeric NOT NULL, CONSTRAINT "PK_637e3f87e837d6532109c198dea" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "token_day_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "token_id" character varying NOT NULL, "volume" numeric NOT NULL, "volume_usd" numeric NOT NULL, "untracked_volume_usd" numeric NOT NULL, "total_value_locked" numeric NOT NULL, "total_value_locked_usd" numeric NOT NULL, "price_usd" numeric NOT NULL, "fees_usd" numeric NOT NULL, "open" numeric NOT NULL, "high" numeric NOT NULL, "low" numeric NOT NULL, "close" numeric NOT NULL, CONSTRAINT "PK_73fc06337215e86196b36822116" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_b8950a8bc7b60231137573740e" ON "token_day_data" ("token_id") `)
    await db.query(`CREATE TABLE "token" ("id" character varying NOT NULL, "symbol" text NOT NULL, "name" text NOT NULL, "decimals" integer NOT NULL, "total_supply" numeric NOT NULL, "volume" numeric NOT NULL, "volume_usd" numeric NOT NULL, "untracked_volume_usd" numeric NOT NULL, "fees_usd" numeric NOT NULL, "tx_count" integer NOT NULL, "pool_count" numeric NOT NULL, "total_value_locked" numeric NOT NULL, "total_value_locked_usd" numeric NOT NULL, "total_value_locked_usd_untracked" numeric NOT NULL, "derived_eth" numeric NOT NULL, "whitelist_pools" text array NOT NULL, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "pool_hour_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "liquidity" numeric NOT NULL, "sqrt_price" numeric NOT NULL, "token0_price" numeric NOT NULL, "token1_price" numeric NOT NULL, "tick" integer, "fee_growth_global0_x128" numeric NOT NULL, "fee_growth_global1_x128" numeric NOT NULL, "tvl_usd" numeric NOT NULL, "volume_token0" numeric NOT NULL, "volume_token1" numeric NOT NULL, "volume_usd" numeric NOT NULL, "fees_usd" numeric NOT NULL, "tx_count" integer NOT NULL, "open" numeric NOT NULL, "high" numeric NOT NULL, "low" numeric NOT NULL, "close" numeric NOT NULL, CONSTRAINT "PK_bd3e248a4a44a474ee2710ec329" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_45e83e45011ed1000559b91726" ON "pool_hour_data" ("pool_id") `)
    await db.query(`CREATE TABLE "pool_day_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "liquidity" numeric NOT NULL, "sqrt_price" numeric NOT NULL, "token0_price" numeric NOT NULL, "token1_price" numeric NOT NULL, "tick" integer, "fee_growth_global0_x128" numeric NOT NULL, "fee_growth_global1_x128" numeric NOT NULL, "tvl_usd" numeric NOT NULL, "volume_token0" numeric NOT NULL, "volume_token1" numeric NOT NULL, "volume_usd" numeric NOT NULL, "fees_usd" numeric NOT NULL, "tx_count" integer NOT NULL, "open" numeric NOT NULL, "high" numeric NOT NULL, "low" numeric NOT NULL, "close" numeric NOT NULL, CONSTRAINT "PK_712b106eb8cc6842af6ca4cab80" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_2f4c9e466537cf8101cbdceaea" ON "pool_day_data" ("pool_id") `)
    await db.query(`CREATE TABLE "burn" ("id" character varying NOT NULL, "transaction_id" character varying NOT NULL, "pool_id" character varying NOT NULL, "token0_id" character varying NOT NULL, "token1_id" character varying NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "owner" text, "origin" text NOT NULL, "amount" numeric NOT NULL, "amount0" numeric NOT NULL, "amount1" numeric NOT NULL, "amount_usd" numeric, "tick_lower" integer NOT NULL, "tick_upper" integer NOT NULL, "log_index" integer, CONSTRAINT "PK_dcb4f14ee4534154b31116553f0" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_20ec76c5c56dd6b47dec5f0aaa" ON "burn" ("transaction_id") `)
    await db.query(`CREATE INDEX "IDX_22b68d0fc4aa2284f6305498d4" ON "burn" ("pool_id") `)
    await db.query(`CREATE INDEX "IDX_beda17e5a9ee09c623adf2b840" ON "burn" ("token0_id") `)
    await db.query(`CREATE INDEX "IDX_08c309f05030028b097cdcd397" ON "burn" ("token1_id") `)
    await db.query(`CREATE TABLE "swap" ("id" character varying NOT NULL, "transaction_id" character varying NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "token0_id" character varying NOT NULL, "token1_id" character varying NOT NULL, "sender" text NOT NULL, "recipient" text NOT NULL, "origin" text NOT NULL, "amount0" numeric NOT NULL, "amount1" numeric NOT NULL, "amount_usd" numeric NOT NULL, "sqrt_price_x96" numeric NOT NULL, "tick" integer NOT NULL, "log_index" integer, CONSTRAINT "PK_4a10d0f359339acef77e7f986d9" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_78506c4050ae7cedd50b08c0dc" ON "swap" ("transaction_id") `)
    await db.query(`CREATE INDEX "IDX_e78e7b899d2e3327494e5fe975" ON "swap" ("pool_id") `)
    await db.query(`CREATE INDEX "IDX_7551fd22a53c8b0c528c6a4b01" ON "swap" ("token0_id") `)
    await db.query(`CREATE INDEX "IDX_63bead532e3e2bc0a56ed362e0" ON "swap" ("token1_id") `)
    await db.query(`CREATE TABLE "flash" ("id" character varying NOT NULL, "transaction_id" character varying NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "sender" text NOT NULL, "recipient" text NOT NULL, "amount0" numeric NOT NULL, "amount1" numeric NOT NULL, "amount_usd" numeric NOT NULL, "amount0_paid" numeric NOT NULL, "amount1_paid" numeric NOT NULL, "log_index" integer, CONSTRAINT "PK_0c01a2c1c5f2266942dd1b3fdbc" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_3be6468a3d651a6fa61868bde5" ON "flash" ("transaction_id") `)
    await db.query(`CREATE INDEX "IDX_e50643ac5b10d7513196cc23ab" ON "flash" ("pool_id") `)
    await db.query(`CREATE TABLE "collect" ("id" character varying NOT NULL, "transaction_id" character varying NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "owner" text, "amount0" numeric NOT NULL, "amount1" numeric NOT NULL, "amount_usd" numeric, "tick_lower" integer NOT NULL, "tick_upper" integer NOT NULL, "log_index" integer, CONSTRAINT "PK_48dc0a6d1738eb0ee8f1e13d3d1" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_7b01351910866ba55a09f4f147" ON "collect" ("transaction_id") `)
    await db.query(`CREATE INDEX "IDX_f2f65641251421bea1e2e771f7" ON "collect" ("pool_id") `)
    await db.query(`CREATE TABLE "transaction" ("id" character varying NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "gas_used" numeric NOT NULL, "gas_price" numeric NOT NULL, CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "mint" ("id" character varying NOT NULL, "transaction_id" character varying NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "token0_id" character varying NOT NULL, "token1_id" character varying NOT NULL, "owner" text NOT NULL, "sender" text, "origin" text NOT NULL, "amount" numeric NOT NULL, "amount0" numeric NOT NULL, "amount1" numeric NOT NULL, "amount_usd" numeric, "tick_lower" integer NOT NULL, "tick_upper" integer NOT NULL, "log_index" integer, CONSTRAINT "PK_fcaea791104aa41aa11dac29cb2" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_19f4328320501dfd14e2bae085" ON "mint" ("transaction_id") `)
    await db.query(`CREATE INDEX "IDX_dbeb28d0d385cca9a032c625ca" ON "mint" ("pool_id") `)
    await db.query(`CREATE INDEX "IDX_f8722de1a52415864f820c0823" ON "mint" ("token0_id") `)
    await db.query(`CREATE INDEX "IDX_43a18dbcccd7c63e5503db63c4" ON "mint" ("token1_id") `)
    await db.query(`CREATE TABLE "tick" ("id" character varying NOT NULL, "pool_address" text, "tick_idx" numeric NOT NULL, "pool_id" character varying NOT NULL, "liquidity_gross" numeric NOT NULL, "liquidity_net" numeric NOT NULL, "price0" numeric NOT NULL, "price1" numeric NOT NULL, "volume_token0" numeric NOT NULL, "volume_token1" numeric NOT NULL, "volume_usd" numeric NOT NULL, "untracked_volume_usd" numeric NOT NULL, "fees_usd" numeric NOT NULL, "collected_fees_token0" numeric NOT NULL, "collected_fees_token1" numeric NOT NULL, "collected_fees_usd" numeric NOT NULL, "created_at_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_block_number" integer NOT NULL, "liquidity_provider_count" numeric NOT NULL, "fee_growth_outside0_x128" numeric NOT NULL, "fee_growth_outside1_x128" numeric NOT NULL, CONSTRAINT "PK_d7e871478c4b671b0c6f1359850" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_ae4af7e6b20e98d01f51cbbcd6" ON "tick" ("pool_id") `)
    await db.query(`CREATE TABLE "pool" ("id" character varying NOT NULL, "created_at_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_block_number" integer NOT NULL, "token0_id" character varying NOT NULL, "token1_id" character varying NOT NULL, "fee_tier" integer NOT NULL, "liquidity" numeric NOT NULL, "sqrt_price" numeric NOT NULL, "fee_growth_global0_x128" numeric NOT NULL, "fee_growth_global1_x128" numeric NOT NULL, "token0_price" numeric NOT NULL, "token1_price" numeric NOT NULL, "tick" integer, "observation_index" numeric NOT NULL, "volume_token0" numeric NOT NULL, "volume_token1" numeric NOT NULL, "volume_usd" numeric NOT NULL, "untracked_volume_usd" numeric NOT NULL, "fees_usd" numeric NOT NULL, "tx_count" integer NOT NULL, "collected_fees_token0" numeric NOT NULL, "collected_fees_token1" numeric NOT NULL, "collected_fees_usd" numeric NOT NULL, "total_value_locked_token0" numeric NOT NULL, "total_value_locked_token1" numeric NOT NULL, "total_value_locked_eth" numeric NOT NULL, "total_value_locked_usd" numeric NOT NULL, "total_value_locked_usd_untracked" numeric NOT NULL, "liquidity_provider_count" numeric NOT NULL, CONSTRAINT "PK_db1bfe411e1516c01120b85f8fe" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_338531367ed63e3eb8e1939980" ON "pool" ("token0_id") `)
    await db.query(`CREATE INDEX "IDX_479321eabdd500587fddd0ee88" ON "pool" ("token1_id") `)
    await db.query(`CREATE TABLE "position" ("id" character varying NOT NULL, "owner" text NOT NULL, "pool_id" character varying NOT NULL, "token0_id" character varying NOT NULL, "token1_id" character varying NOT NULL, "liquidity" numeric NOT NULL, "deposited_token0" numeric NOT NULL, "deposited_token1" numeric NOT NULL, "withdrawn_token0" numeric NOT NULL, "withdrawn_token1" numeric NOT NULL, "collected_fees_token0" numeric NOT NULL, "collected_fees_token1" numeric NOT NULL, "fee_growth_inside0_last_x128" numeric NOT NULL, "fee_growth_inside1_last_x128" numeric NOT NULL, CONSTRAINT "PK_b7f483581562b4dc62ae1a5b7e2" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_128820371117dcf3915dc01ad3" ON "position" ("pool_id") `)
    await db.query(`CREATE INDEX "IDX_f230b92ea5e4bdf8bd6658c629" ON "position" ("token0_id") `)
    await db.query(`CREATE INDEX "IDX_32d393d9b4c15d1f3253445453" ON "position" ("token1_id") `)
    await db.query(`CREATE TABLE "position_snapshot" ("id" character varying NOT NULL, "owner" text NOT NULL, "pool_id" character varying NOT NULL, "position_id" character varying NOT NULL, "block_number" integer NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "liquidity" numeric NOT NULL, "deposited_token0" numeric NOT NULL, "deposited_token1" numeric NOT NULL, "withdrawn_token0" numeric NOT NULL, "withdrawn_token1" numeric NOT NULL, "collected_fees_token0" numeric NOT NULL, "collected_fees_token1" numeric NOT NULL, "transaction_id" character varying NOT NULL, "fee_growth_inside0_last_x128" numeric NOT NULL, "fee_growth_inside1_last_x128" numeric NOT NULL, CONSTRAINT "PK_1988663621abbe6aca0301178b8" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_016de40c4f8b13ccf15f9209b7" ON "position_snapshot" ("pool_id") `)
    await db.query(`CREATE INDEX "IDX_517394d79735819c6c0912d484" ON "position_snapshot" ("position_id") `)
    await db.query(`CREATE INDEX "IDX_e7b0099f3c24660dd87abef310" ON "position_snapshot" ("transaction_id") `)
    await db.query(`CREATE TABLE "uniswap_day_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "volume_eth" numeric NOT NULL, "volume_usd" numeric NOT NULL, "volume_usd_untracked" numeric NOT NULL, "fees_usd" numeric NOT NULL, "tx_count" integer NOT NULL, "tvl_usd" numeric NOT NULL, CONSTRAINT "PK_f1c3f2aa9a6830b502f2602744e" PRIMARY KEY ("id"))`)
    await db.query(`CREATE TABLE "tick_hour_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "pool_id" character varying NOT NULL, "tick_id" character varying NOT NULL, "liquidity_gross" numeric NOT NULL, "liquidity_net" numeric NOT NULL, "volume_token0" numeric NOT NULL, "volume_token1" numeric NOT NULL, "volume_usd" numeric NOT NULL, "fees_usd" numeric NOT NULL, CONSTRAINT "PK_6d007da7044231b7ba6fd1ae283" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_a8ec49fdef1dd74e8686663d3b" ON "tick_hour_data" ("pool_id") `)
    await db.query(`CREATE INDEX "IDX_960aad2a930d28f639e8f76cca" ON "tick_hour_data" ("tick_id") `)
    await db.query(`CREATE TABLE "tick_day_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "tick_id" character varying NOT NULL, "liquidity_gross" numeric NOT NULL, "liquidity_net" numeric NOT NULL, "volume_token0" numeric NOT NULL, "volume_token1" numeric NOT NULL, "volume_usd" numeric NOT NULL, "fees_usd" numeric NOT NULL, "fee_growth_outside0_x128" numeric NOT NULL, "fee_growth_outside1_x128" numeric NOT NULL, CONSTRAINT "PK_f1c2b25e4010234c9b4b1b97b1b" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_b835aa3d56244f4e9120bf7c88" ON "tick_day_data" ("tick_id") `)
    await db.query(`CREATE TABLE "token_hour_data" ("id" character varying NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "token_id" character varying NOT NULL, "volume" numeric NOT NULL, "volume_usd" numeric NOT NULL, "untracked_volume_usd" numeric NOT NULL, "total_value_locked" numeric NOT NULL, "total_value_locked_usd" numeric NOT NULL, "price_usd" numeric NOT NULL, "fees_usd" numeric NOT NULL, "open" numeric NOT NULL, "high" numeric NOT NULL, "low" numeric NOT NULL, "close" numeric NOT NULL, CONSTRAINT "PK_c05e57412a0166a5b8558d6e796" PRIMARY KEY ("id"))`)
    await db.query(`CREATE INDEX "IDX_7080974648c0d2c3baceb239c4" ON "token_hour_data" ("token_id") `)
    await db.query(`ALTER TABLE "token_day_data" ADD CONSTRAINT "FK_b8950a8bc7b60231137573740ea" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "pool_hour_data" ADD CONSTRAINT "FK_45e83e45011ed1000559b91726f" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "pool_day_data" ADD CONSTRAINT "FK_2f4c9e466537cf8101cbdceaea1" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "burn" ADD CONSTRAINT "FK_20ec76c5c56dd6b47dec5f0aaa8" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "burn" ADD CONSTRAINT "FK_22b68d0fc4aa2284f6305498d4e" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "burn" ADD CONSTRAINT "FK_beda17e5a9ee09c623adf2b840b" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "burn" ADD CONSTRAINT "FK_08c309f05030028b097cdcd3974" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_78506c4050ae7cedd50b08c0dc5" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_e78e7b899d2e3327494e5fe975d" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_7551fd22a53c8b0c528c6a4b010" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_63bead532e3e2bc0a56ed362e0c" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "flash" ADD CONSTRAINT "FK_3be6468a3d651a6fa61868bde50" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "flash" ADD CONSTRAINT "FK_e50643ac5b10d7513196cc23ab6" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "collect" ADD CONSTRAINT "FK_7b01351910866ba55a09f4f147a" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "collect" ADD CONSTRAINT "FK_f2f65641251421bea1e2e771f74" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "mint" ADD CONSTRAINT "FK_19f4328320501dfd14e2bae0855" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "mint" ADD CONSTRAINT "FK_dbeb28d0d385cca9a032c625cad" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "mint" ADD CONSTRAINT "FK_f8722de1a52415864f820c08231" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "mint" ADD CONSTRAINT "FK_43a18dbcccd7c63e5503db63c43" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "tick" ADD CONSTRAINT "FK_ae4af7e6b20e98d01f51cbbcd69" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_338531367ed63e3eb8e1939980f" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_479321eabdd500587fddd0ee88b" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_128820371117dcf3915dc01ad30" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_f230b92ea5e4bdf8bd6658c6292" FOREIGN KEY ("token0_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "position" ADD CONSTRAINT "FK_32d393d9b4c15d1f3253445453e" FOREIGN KEY ("token1_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "position_snapshot" ADD CONSTRAINT "FK_016de40c4f8b13ccf15f9209b7b" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "position_snapshot" ADD CONSTRAINT "FK_517394d79735819c6c0912d4840" FOREIGN KEY ("position_id") REFERENCES "position"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "position_snapshot" ADD CONSTRAINT "FK_e7b0099f3c24660dd87abef310c" FOREIGN KEY ("transaction_id") REFERENCES "transaction"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "tick_hour_data" ADD CONSTRAINT "FK_a8ec49fdef1dd74e8686663d3bb" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "tick_hour_data" ADD CONSTRAINT "FK_960aad2a930d28f639e8f76ccaf" FOREIGN KEY ("tick_id") REFERENCES "tick"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "tick_day_data" ADD CONSTRAINT "FK_b835aa3d56244f4e9120bf7c88e" FOREIGN KEY ("tick_id") REFERENCES "tick"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    await db.query(`ALTER TABLE "token_hour_data" ADD CONSTRAINT "FK_7080974648c0d2c3baceb239c4e" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
  }

  async down(db) {
    await db.query(`DROP TABLE "factory"`)
    await db.query(`DROP TABLE "bundle"`)
    await db.query(`DROP TABLE "token_day_data"`)
    await db.query(`DROP INDEX "public"."IDX_b8950a8bc7b60231137573740e"`)
    await db.query(`DROP TABLE "token"`)
    await db.query(`DROP TABLE "pool_hour_data"`)
    await db.query(`DROP INDEX "public"."IDX_45e83e45011ed1000559b91726"`)
    await db.query(`DROP TABLE "pool_day_data"`)
    await db.query(`DROP INDEX "public"."IDX_2f4c9e466537cf8101cbdceaea"`)
    await db.query(`DROP TABLE "burn"`)
    await db.query(`DROP INDEX "public"."IDX_20ec76c5c56dd6b47dec5f0aaa"`)
    await db.query(`DROP INDEX "public"."IDX_22b68d0fc4aa2284f6305498d4"`)
    await db.query(`DROP INDEX "public"."IDX_beda17e5a9ee09c623adf2b840"`)
    await db.query(`DROP INDEX "public"."IDX_08c309f05030028b097cdcd397"`)
    await db.query(`DROP TABLE "swap"`)
    await db.query(`DROP INDEX "public"."IDX_78506c4050ae7cedd50b08c0dc"`)
    await db.query(`DROP INDEX "public"."IDX_e78e7b899d2e3327494e5fe975"`)
    await db.query(`DROP INDEX "public"."IDX_7551fd22a53c8b0c528c6a4b01"`)
    await db.query(`DROP INDEX "public"."IDX_63bead532e3e2bc0a56ed362e0"`)
    await db.query(`DROP TABLE "flash"`)
    await db.query(`DROP INDEX "public"."IDX_3be6468a3d651a6fa61868bde5"`)
    await db.query(`DROP INDEX "public"."IDX_e50643ac5b10d7513196cc23ab"`)
    await db.query(`DROP TABLE "collect"`)
    await db.query(`DROP INDEX "public"."IDX_7b01351910866ba55a09f4f147"`)
    await db.query(`DROP INDEX "public"."IDX_f2f65641251421bea1e2e771f7"`)
    await db.query(`DROP TABLE "transaction"`)
    await db.query(`DROP TABLE "mint"`)
    await db.query(`DROP INDEX "public"."IDX_19f4328320501dfd14e2bae085"`)
    await db.query(`DROP INDEX "public"."IDX_dbeb28d0d385cca9a032c625ca"`)
    await db.query(`DROP INDEX "public"."IDX_f8722de1a52415864f820c0823"`)
    await db.query(`DROP INDEX "public"."IDX_43a18dbcccd7c63e5503db63c4"`)
    await db.query(`DROP TABLE "tick"`)
    await db.query(`DROP INDEX "public"."IDX_ae4af7e6b20e98d01f51cbbcd6"`)
    await db.query(`DROP TABLE "pool"`)
    await db.query(`DROP INDEX "public"."IDX_338531367ed63e3eb8e1939980"`)
    await db.query(`DROP INDEX "public"."IDX_479321eabdd500587fddd0ee88"`)
    await db.query(`DROP TABLE "position"`)
    await db.query(`DROP INDEX "public"."IDX_128820371117dcf3915dc01ad3"`)
    await db.query(`DROP INDEX "public"."IDX_f230b92ea5e4bdf8bd6658c629"`)
    await db.query(`DROP INDEX "public"."IDX_32d393d9b4c15d1f3253445453"`)
    await db.query(`DROP TABLE "position_snapshot"`)
    await db.query(`DROP INDEX "public"."IDX_016de40c4f8b13ccf15f9209b7"`)
    await db.query(`DROP INDEX "public"."IDX_517394d79735819c6c0912d484"`)
    await db.query(`DROP INDEX "public"."IDX_e7b0099f3c24660dd87abef310"`)
    await db.query(`DROP TABLE "uniswap_day_data"`)
    await db.query(`DROP TABLE "tick_hour_data"`)
    await db.query(`DROP INDEX "public"."IDX_a8ec49fdef1dd74e8686663d3b"`)
    await db.query(`DROP INDEX "public"."IDX_960aad2a930d28f639e8f76cca"`)
    await db.query(`DROP TABLE "tick_day_data"`)
    await db.query(`DROP INDEX "public"."IDX_b835aa3d56244f4e9120bf7c88"`)
    await db.query(`DROP TABLE "token_hour_data"`)
    await db.query(`DROP INDEX "public"."IDX_7080974648c0d2c3baceb239c4"`)
    await db.query(`ALTER TABLE "token_day_data" DROP CONSTRAINT "FK_b8950a8bc7b60231137573740ea"`)
    await db.query(`ALTER TABLE "pool_hour_data" DROP CONSTRAINT "FK_45e83e45011ed1000559b91726f"`)
    await db.query(`ALTER TABLE "pool_day_data" DROP CONSTRAINT "FK_2f4c9e466537cf8101cbdceaea1"`)
    await db.query(`ALTER TABLE "burn" DROP CONSTRAINT "FK_20ec76c5c56dd6b47dec5f0aaa8"`)
    await db.query(`ALTER TABLE "burn" DROP CONSTRAINT "FK_22b68d0fc4aa2284f6305498d4e"`)
    await db.query(`ALTER TABLE "burn" DROP CONSTRAINT "FK_beda17e5a9ee09c623adf2b840b"`)
    await db.query(`ALTER TABLE "burn" DROP CONSTRAINT "FK_08c309f05030028b097cdcd3974"`)
    await db.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_78506c4050ae7cedd50b08c0dc5"`)
    await db.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_e78e7b899d2e3327494e5fe975d"`)
    await db.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_7551fd22a53c8b0c528c6a4b010"`)
    await db.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_63bead532e3e2bc0a56ed362e0c"`)
    await db.query(`ALTER TABLE "flash" DROP CONSTRAINT "FK_3be6468a3d651a6fa61868bde50"`)
    await db.query(`ALTER TABLE "flash" DROP CONSTRAINT "FK_e50643ac5b10d7513196cc23ab6"`)
    await db.query(`ALTER TABLE "collect" DROP CONSTRAINT "FK_7b01351910866ba55a09f4f147a"`)
    await db.query(`ALTER TABLE "collect" DROP CONSTRAINT "FK_f2f65641251421bea1e2e771f74"`)
    await db.query(`ALTER TABLE "mint" DROP CONSTRAINT "FK_19f4328320501dfd14e2bae0855"`)
    await db.query(`ALTER TABLE "mint" DROP CONSTRAINT "FK_dbeb28d0d385cca9a032c625cad"`)
    await db.query(`ALTER TABLE "mint" DROP CONSTRAINT "FK_f8722de1a52415864f820c08231"`)
    await db.query(`ALTER TABLE "mint" DROP CONSTRAINT "FK_43a18dbcccd7c63e5503db63c43"`)
    await db.query(`ALTER TABLE "tick" DROP CONSTRAINT "FK_ae4af7e6b20e98d01f51cbbcd69"`)
    await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_338531367ed63e3eb8e1939980f"`)
    await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_479321eabdd500587fddd0ee88b"`)
    await db.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_128820371117dcf3915dc01ad30"`)
    await db.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_f230b92ea5e4bdf8bd6658c6292"`)
    await db.query(`ALTER TABLE "position" DROP CONSTRAINT "FK_32d393d9b4c15d1f3253445453e"`)
    await db.query(`ALTER TABLE "position_snapshot" DROP CONSTRAINT "FK_016de40c4f8b13ccf15f9209b7b"`)
    await db.query(`ALTER TABLE "position_snapshot" DROP CONSTRAINT "FK_517394d79735819c6c0912d4840"`)
    await db.query(`ALTER TABLE "position_snapshot" DROP CONSTRAINT "FK_e7b0099f3c24660dd87abef310c"`)
    await db.query(`ALTER TABLE "tick_hour_data" DROP CONSTRAINT "FK_a8ec49fdef1dd74e8686663d3bb"`)
    await db.query(`ALTER TABLE "tick_hour_data" DROP CONSTRAINT "FK_960aad2a930d28f639e8f76ccaf"`)
    await db.query(`ALTER TABLE "tick_day_data" DROP CONSTRAINT "FK_b835aa3d56244f4e9120bf7c88e"`)
    await db.query(`ALTER TABLE "token_hour_data" DROP CONSTRAINT "FK_7080974648c0d2c3baceb239c4e"`)
  }
}
